preload = /home/akeka/Documents/wallpapers/debian_grey_swirl.png
wallpaper {
    monitor = DP-1
    path = /home/akeka/Documents/wallpapers/debian_grey_swirl.png
    # fit_mode is optional; defaults to "cover"
    # fit_mode = cover
}
wallpaper {
    monitor = DP-2
    path = /home/akeka/Documents/wallpapers/debian_grey_swirl.png
}
splash = false
